annotation_gff: pipeline/annotation/C_albicans_SC5314_A21_current_features.gff
genome_dir: data/ca_genome
metadata: data/metadata.xlsx
polya_ref: pipeline/polyA.fa.gz
raw_fastq_dir: data/raw
results_dir: results
threads: 8
truseq_ref: pipeline/truseq.fa.gz
